{ id: 'presupuestos', label: 'Presupuestos', href: '/presupuestos', icon: 'doc' },
{ id: 'envios',       label: 'Envíos',       href: '/envios',       icon: 'truck' },
{ id: 'produccion',   label: 'Cola de producción', href: '/produccion', icon: 'calendar' },
{ id: 'archivos',     label: 'Archivos y diseños', href: '/archivos',   icon: 'folder' },
{ id: 'reportes',     label: 'Reportes',     href: '/reportes',     icon: 'report' },
